services:
  mysql:
    image: mysql:8.0
    volumes:
    - jpaMySQL:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=jpaMySQL
    ports:
    - "3306:3306"
    restart: always


  forumapp:
    image: forum-with-mysql
    ports:
    - "8080:8080"
    entrypoint: ["java","-jar","/app.jar"]
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/jpaMySQL
    depends_on:
      - mysql
    restart: always
volumes:
  jpaMySQL: